source 'https://rubygems.org'

gem 'cucumber'
gem 'git'
gem 'k8s-client'
gem 'mustache'
gem 'net-ssh'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rubocop'
gem 'sinatra'
gem 'slim'
gem 'sshkey'
gem 'thin'
gem 'uri-ssh_git'
gem 'coveralls', require: false
